services:
  - name: app
    buildCommand: ""
    startCommand: ""
    env: 
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: postgres
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
    envVars:
      - name: PORT
        value: 8080
    dockerfile: Dockerfile
    github:
      branch: main
      repo: yourusername/your-repo
  - name: db
    env:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: postgres
    image: postgres:latest
